In [23]:
import pandas as pd

In [ ]:
df = pd.read_csv('..//project_data//raw//nifty50//nifty50_raw.csv')
df.head()

,Unnamed: 0,Date,Adj Close,Close,High,Low,Open,Volume
0,0,2021-08-13,16529.099609,16529.099609,16543.599609,16376.299805,16385.699219,321900
1,1,2021-08-16,16563.050781,16563.050781,16589.400391,16480.750000,16518.400391,254000
2,2,2021-08-17,16614.599609,16614.599609,16628.550781,16495.400391,16545.250000,297400
3,3,2021-08-18,16568.849609,16568.849609,16701.849609,16535.849609,16691.949219,251800
4,4,2021-08-20,16450.500000,16450.500000,16509.550781,16376.049805,16382.500000,350800

In [2]:
import os
print(os.getcwd())

d:\MarketPulse-AI\notebooks

In [31]:
df.columns

Index(['Unnamed: 0', 'Date', 'Adj Close', 'Close', 'High', 'Low', 'Open',
       'Volume'],
      dtype='str')

In [35]:
df = df.drop(columns = ['Unnamed: 0'])

In [36]:
df.columns.to_list()

['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

In [37]:
df.shape

(1235, 7)

In [38]:
df.isnull().sum()

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1235 entries, 0 to 1234
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1235 non-null   str
 1   Adj Close  1235 non-null   float64
 2   Close      1235 non-null   float64
 3   High       1235 non-null   float64
 4   Low        1235 non-null   float64
 5   Open       1235 non-null   float64
 6   Volume     1235 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 67.7 KB

In [40]:
df.empty

False

In [42]:
columns = ['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

missing_cols = [col for col in columns if col not in df.columns]
print('missing_columns:', missing_cols)

validation_status = len(missing_cols) == 0 and not df.empty
print("validation status:", validation_status)

missing_columns: []
validation status: True

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df['Date'] = pd.to_datetime(df['Date'])

print('start_date:', df['Date'].min())
print('end date:', df['Date'].max())

start_date: 2021-08-13 00:00:00
end date: 2026-08-13 00:00:00

In [45]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Shape: (1235, 7)

Columns:
['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

Data types:
Date         datetime64[us]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

Missing values:
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

Duplicate rows:
0

In [46]:
df["Date"] = pd.to_datetime(df["Date"])

print("\nDuplicate dates:")
print(df["Date"].duplicated().sum())

print("\nDates sorted:")
print(df["Date"].is_monotonic_increasing)

Duplicate dates:
0

Dates sorted:
True

In [47]:
price_columns = ["Open", "High", "Low", "Close"]

for column in price_columns:
    print(
        column,
        "invalid values:",
        (df[column] <= 0).sum()
    )

Open invalid values: 0
High invalid values: 0
Low invalid values: 0
Close invalid values: 0

In [49]:
print(df[["Open", "High", "Low", "Close"]].dtypes)

Open     float64
High     float64
Low      float64
Close    float64
dtype: object

In [4]:
import pandas as pd
df = pd.read_csv(
    "../project_data/processed/nifty50/nifty50_transformed.csv"
)

print(df.shape)
print(df.head())
print(df.tail())
print(df["Target"].value_counts())

(1234, 7)
         Date          Open          High           Low         Close  Volume  \
0  2021-08-13  16385.699219  16543.599609  16376.299805  16529.099609  321900
1  2021-08-16  16518.400391  16589.400391  16480.750000  16563.050781  254000
2  2021-08-17  16545.250000  16628.550781  16495.400391  16614.599609  297400
3  2021-08-18  16691.949219  16701.849609  16535.849609  16568.849609  251800
4  2021-08-20  16382.500000  16509.550781  16376.049805  16450.500000  350800

   Target
0       1
1       1
2       0
3       0
4       1
            Date          Open          High           Low         Close  \
1229  2026-08-06  24641.000000  24677.050781  24604.150391  24636.000000
1230  2026-08-07  24538.900391  24630.400391  24522.750000  24570.650391
1231  2026-08-10  24581.250000  24620.949219  24511.099609  24583.800781
1232  2026-08-11  24575.099609  24576.849609  24429.250000  24471.699219
1233  2026-08-12  24472.449219  24473.300781  24265.949219  24435.949219

      Volume  Target
1229  344000       0
1230  254800       1
1231  269500       0
1232  271800       0
1233  317600       0
Target
1    653
0    581
Name: count, dtype: int64

In [3]:
import os
print(os.getcwd())

d:\MarketPulse-AI\notebooks

In [6]:
import pandas as pd

feature_data_path = (
    "../project_data/processed/nifty50/nifty50_features.csv"
)

df = pd.read_csv(feature_data_path)

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nTarget distribution:")
print(df["Target"].value_counts())

print("\nFirst 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

Shape: (1183, 35)

Columns:
['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Daily_Return', 'Log_Return', 'High_Low_Range', 'Open_Close_Change', 'SMA_5', 'SMA_20', 'SMA_50', 'EMA_20', 'EMA_50', 'Price_SMA20_Ratio', 'Price_SMA50_Ratio', 'SMA20_SMA50_Ratio', 'Momentum_10', 'RSI_14', 'MACD', 'MACD_Signal', 'MACD_Histogram', 'Volatility_10', 'Volatility_20', 'ATR_14', 'Volume_Change', 'Volume_SMA_20', 'Relative_Volume', 'Return_Lag_1', 'Return_Lag_2', 'Return_Lag_3', 'Return_Lag_5', 'Volume_Lag_1', 'Target']

Missing values:
0

Target distribution:
Target
1    620
0    563
Name: count, dtype: int64

First 5 rows:
         Date          Open          High           Low         Close  Volume  \
0  2021-10-26  18154.500000  18310.449219  18099.300781  18268.400391  341400
1  2021-10-27  18295.849609  18342.050781  18167.900391  18210.949219  335200
2  2021-10-28  18187.650391  18190.699219  17799.449219  17857.250000  374200
3  2021-10-29  17833.050781  17915.849609  17613.099609  17671.650391  336500
4  2021-11-01  17783.150391  17954.099609  17697.099609  17929.650391  281200

   Daily_Return  Log_Return  High_Low_Range  Open_Close_Change  ...  \
0      0.007889    0.007859        0.011558           0.006274  ...
1     -0.003145   -0.003150        0.009563          -0.004640  ...
2     -0.019422   -0.019613        0.021910          -0.018166  ...
3     -0.010394   -0.010448        0.017132          -0.009051  ...
4      0.014600    0.014494        0.014334           0.008238  ...

       ATR_14  Volume_Change  Volume_SMA_20  Relative_Volume  Return_Lag_1  \
0  225.453683      -0.184619       397205.0         0.859506      0.000580
1  218.503767      -0.018161       394065.0         0.850621      0.007889
2  231.339425       0.116348       384665.0         0.972795     -0.003145
3  242.142997      -0.100748       382560.0         0.879601     -0.019422
4  247.828683      -0.164339       381330.0         0.737419     -0.010394

   Return_Lag_2  Return_Lag_3  Return_Lag_5  Volume_Lag_1  Target
0     -0.003477     -0.004845     -0.003155      418700.0       0
1      0.000580     -0.003477     -0.008261      341400.0       0
2      0.007889      0.000580     -0.004845      335200.0       0
3     -0.003145      0.007889     -0.003477      374200.0       1
4     -0.019422     -0.003145      0.000580      336500.0       0

[5 rows x 35 columns]

Last 5 rows:
            Date          Open          High           Low         Close  \
1178  2026-08-06  24641.000000  24677.050781  24604.150391  24636.000000
1179  2026-08-07  24538.900391  24630.400391  24522.750000  24570.650391
1180  2026-08-10  24581.250000  24620.949219  24511.099609  24583.800781
1181  2026-08-11  24575.099609  24576.849609  24429.250000  24471.699219
1182  2026-08-12  24472.449219  24473.300781  24265.949219  24435.949219

      Volume  Daily_Return  Log_Return  High_Low_Range  Open_Close_Change  \
1178  344000      0.000461    0.000461        0.002959          -0.000203
1179  254800     -0.002653   -0.002656        0.004381           0.001294
1180  269500      0.000535    0.000535        0.004468           0.000104
1181  271800     -0.004560   -0.004570        0.006031          -0.004208
1182  317600     -0.001461   -0.001462        0.008486          -0.001491

      ...      ATR_14  Volume_Change  Volume_SMA_20  Relative_Volume  \
1178  ...  192.586077      -0.032349       346695.0         0.992227
1179  ...  190.971819      -0.259302       343780.0         0.741172
1180  ...  189.779018       0.057692       341120.0         0.790045
1181  ...  185.686105       0.008534       336920.0         0.806720
1182  ...  187.386161       0.168506       337455.0         0.941163

      Return_Lag_1  Return_Lag_2  Return_Lag_3  Return_Lag_5  Volume_Lag_1  \
1178      0.000396     -0.006434      0.016023      0.002761      355500.0
1179      0.000461      0.000396     -0.006434      0.002733      344000.0
1180     -0.002653      0.000461      0.000396      0.016023      254800.0
1181      0.000535     -0.002653      0.000461     -0.006434      269500.0
1182     -0.004560      0.000535     -0.002653      0.000396      271800.0

      Target
1178       0
1179       1
1180       0
1181       0
1182       0

[5 rows x 35 columns]

In [7]:
df = pd.read_csv('../project_data/train/train.csv')
df

,Date,Open,High,Low,Close,Volume,Daily_Return,Log_Return,High_Low_Range,Open_Close_Change,...,ATR_14,Volume_Change,Volume_SMA_20,Relative_Volume,Return_Lag_1,Return_Lag_2,Return_Lag_3,Return_Lag_5,Volume_Lag_1,Target
0,2021-10-26,18154.500000,18310.449219,18099.300781,18268.400391,341400,0.007889,0.007859,0.011558,0.006274,...,225.453683,-0.184619,397205.0,0.859506,0.000580,-0.003477,-0.004845,-0.003155,418700.0,0
1,2021-10-27,18295.849609,18342.050781,18167.900391,18210.949219,335200,-0.003145,-0.003150,0.009563,-0.004640,...,218.503767,-0.018161,394065.0,0.850621,0.007889,0.000580,-0.003477,-0.008261,341400.0,0
2,2021-10-28,18187.650391,18190.699219,17799.449219,17857.250000,374200,-0.019422,-0.019613,0.021910,-0.018166,...,231.339425,0.116348,384665.0,0.972795,-0.003145,0.007889,0.000580,-0.004845,335200.0,0
3,2021-10-29,17833.050781,17915.849609,17613.099609,17671.650391,336500,-0.010394,-0.010448,0.017132,-0.009051,...,242.142997,-0.100748,382560.0,0.879601,-0.019422,-0.003145,0.007889,-0.003477,374200.0,1
4,2021-11-01,17783.150391,17954.099609,17697.099609,17929.650391,281200,0.014600,0.014494,0.014334,0.008238,...,247.828683,-0.164339,381330.0,0.737419,-0.010394,-0.019422,-0.003145,0.000580,336500.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
823,2025-02-24,22609.349609,22668.050781,22518.800781,22553.349609,214300,-0.010640,-0.010697,0.006618,-0.002477,...,238.253627,-0.117381,272380.0,0.786768,-0.005117,-0.000861,-0.000540,0.001319,242800.0,0
824,2025-02-25,22516.449219,22625.300781,22513.900391,22547.550781,250300,-0.000257,-0.000257,0.004941,0.001381,...,237.149972,0.167989,273580.0,0.914906,-0.010640,-0.005117,-0.000861,-0.000618,214300.0,0
825,2025-02-27,22568.949219,22613.300781,22508.400391,22545.050781,289200,-0.000111,-0.000111,0.004653,-0.001059,...,229.121373,0.155414,269945.0,1.071329,-0.000257,-0.010640,-0.005117,-0.000540,250300.0,0
826,2025-02-28,22433.400391,22450.349609,22104.849609,22124.699219,551300,-0.018645,-0.018821,0.015616,-0.013761,...,235.849888,0.906293,282265.0,1.953129,-0.000111,-0.000257,-0.010640,-0.000861,289200.0,0
827,2025-03-03,22194.550781,22261.550781,22004.699219,22119.300781,282400,-0.000244,-0.000244,0.011612,-0.003390,...,236.175084,-0.487756,282335.0,1.000230,-0.018645,-0.000111,-0.000257,-0.005117,551300.0,0

In [9]:
import numpy as np

np.isinf(df.select_dtypes(include=np.number)).sum()

Open                 0
High                 0
Low                  0
Close                0
Volume               0
Daily_Return         0
Log_Return           0
High_Low_Range       0
Open_Close_Change    0
SMA_5                0
SMA_20               0
SMA_50               0
EMA_20               0
EMA_50               0
Price_SMA20_Ratio    0
Price_SMA50_Ratio    0
SMA20_SMA50_Ratio    0
Momentum_10          0
RSI_14               0
MACD                 0
MACD_Signal          0
MACD_Histogram       0
Volatility_10        0
Volatility_20        0
ATR_14               0
Volume_Change        6
Volume_SMA_20        0
Relative_Volume      0
Return_Lag_1         0
Return_Lag_2         0
Return_Lag_3         0
Return_Lag_5         0
Volume_Lag_1         0
Target               0
dtype: int64

In [10]:
target_column = "Target"

x_train = df.drop(columns=[target_column, "Date"])
y_train = df[target_column]

In [11]:
x_train.dtypes

Open                 float64
High                 float64
Low                  float64
Close                float64
Volume                 int64
Daily_Return         float64
Log_Return           float64
High_Low_Range       float64
Open_Close_Change    float64
SMA_5                float64
SMA_20               float64
SMA_50               float64
EMA_20               float64
EMA_50               float64
Price_SMA20_Ratio    float64
Price_SMA50_Ratio    float64
SMA20_SMA50_Ratio    float64
Momentum_10          float64
RSI_14               float64
MACD                 float64
MACD_Signal          float64
MACD_Histogram       float64
Volatility_10        float64
Volatility_20        float64
ATR_14               float64
Volume_Change        float64
Volume_SMA_20        float64
Relative_Volume      float64
Return_Lag_1         float64
Return_Lag_2         float64
Return_Lag_3         float64
Return_Lag_5         float64
Volume_Lag_1         float64
dtype: object

In [13]:
x_train.max().sort_values(ascending=False)

Volume_Change                 inf
Volume_Lag_1         1.006100e+06
Volume               1.006100e+06
Volume_SMA_20        4.170900e+05
High                 2.627735e+04
Open                 2.624825e+04
Close                2.621605e+04
Low                  2.615140e+04
SMA_5                2.605572e+04
EMA_20               2.558720e+04
SMA_20               2.550808e+04
SMA_50               2.512805e+04
EMA_50               2.506674e+04
MACD                 4.510834e+02
ATR_14               4.503324e+02
MACD_Signal          4.139853e+02
MACD_Histogram       1.300943e+02
RSI_14               1.000000e+02
Relative_Volume      2.849092e+00
Price_SMA50_Ratio    1.094770e+00
Price_SMA20_Ratio    1.060304e+00
SMA20_SMA50_Ratio    1.055554e+00
Momentum_10          9.155493e-02
High_Low_Range       8.673037e-02
Daily_Return         3.362424e-02
Return_Lag_3         3.362424e-02
Return_Lag_5         3.362424e-02
Return_Lag_1         3.362424e-02
Return_Lag_2         3.362424e-02
Log_Return           3.307130e-02
Volatility_10        2.685818e-02
Open_Close_Change    2.475598e-02
Volatility_20        1.904681e-02
dtype: float64

In [15]:
df[df["Volume"] == 0][["Date", "Volume"]]

           Date  Volume
200  2022-08-16       0
350  2023-03-22       0
448  2023-08-16       0
573  2024-02-19       0
600  2024-04-01       0
660  2024-07-01       0

In [16]:
df[df["Volume_Change"] == np.inf][
    ["Date", "Volume", "Volume_Change"]
]

           Date  Volume  Volume_Change
201  2022-08-17  262800            inf
351  2023-03-23  219200            inf
449  2023-08-17  268700            inf
574  2024-02-20  295700            inf
601  2024-04-02  289500            inf
661  2024-07-04  251200            inf

In [19]:
import pandas as pd

df = pd.read_csv(
    "../project_data/processed/nifty50/nifty50_features.csv"
)

print("Feature dataset:", df.shape)
print("Train:", len(pd.read_csv("../project_data/train/train.csv")))
print("Validation:", len(pd.read_csv("../project_data/validation/validation.csv")))
print("Test:", len(pd.read_csv("../project_data/test/test.csv")))

Feature dataset: (1185, 35)
Train: 829
Validation: 177
Test: 179

In [20]:
from MarketPulse_AI_project.components.sequence_creation import SequenceCreation
sequence_creator = SequenceCreation(sequence_length=30)

X_train_seq, y_train_seq = sequence_creator.create_sequence(
    x_train_scaled,
    y_train
)

X_validation_seq, y_validation_seq = sequence_creator.create_sequence(
    x_validation_scaled,
    y_validation
)

X_test_seq, y_test_seq = sequence_creator.create_sequence(
    x_test_scaled,
    y_test
)

NameError: name 'x_train_scaled' is not defined